/*
Enter your query here.
*/
SELECT WANDS.ID,WANDS_PROPERTY.AGE,WANDS.COINS_NEEDED,WANDS.POWER
FROM WANDS
    JOIN WANDS_PROPERTY
        ON WANDS.CODE = WANDS_PROPERTY.CODE
WHERE WANDS_PROPERTY.IS_EVIL = 0 AND WANDS.COINS_NEEDED = (
    SELECT MIN(COINS_NEEDED) 
    FROM WANDS AS W 
        JOIN WANDS_PROPERTY AS P 
            ON (W.CODE = P.CODE) 
    WHERE W.POWER = WANDS.POWER and P.AGE = WANDS_PROPERTY.AGE)
ORDER BY WANDS.POWER DESC, WANDS_PROPERTY.AGE DESC