/*
Enter your query here.
*/
SELECT HACKERS.HACKER_ID,HACKERS.NAME 
FROM SUBMISSIONS 
    JOIN CHALLENGES 
        ON SUBMISSIONS.CHALLENGE_ID = CHALLENGES.CHALLENGE_ID
    JOIN DIFFICULTY
        ON CHALLENGES.DIFFICULTY_LEVEL = DIFFICULTY.DIFFICULTY_LEVEL
    JOIN HACKERS
        ON SUBMISSIONS.HACKER_ID = HACKERS.HACKER_ID
WHERE SUBMISSIONS.SCORE = DIFFICULTY.SCORE
GROUP BY SUBMISSIONS.HACKER_ID,HACKERS.NAME HAVING COUNT(SUBMISSIONS.SCORE) > 1
ORDER BY COUNT(SUBMISSIONS.SCORE) DESC,HACKERS.HACKER_ID;