/*
Enter your query here.
*/
SELECT CONCAT(NAME,'(',SUBSTR(OCCUPATION,1,1),')') AS NAME FROM OCCUPATIONS ORDER BY NAME;
SELECT CONCAT('There are total ', COUNT(OCCUPATION), ' ', LOWER(OCCUPATION), 's.') AS TOTAL FROM OCCUPATIONS GROUP BY OCCUPATION ORDER BY TOTAL;